apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2023-11-16T20:16:04Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.autoscaling
  resourceVersion: "17"
  uid: 7bd01614-cde8-4bd6-9ec7-c6478a388a82
spec:
  group: autoscaling
  groupPriorityMinimum: 17500
  version: v1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2023-11-16T20:16:04Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
