apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2023-11-16T20:16:04Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.storage.k8s.io
  resourceVersion: "37"
  uid: 40a668e2-8d4b-4558-a62d-f9eee153a5f1
spec:
  group: storage.k8s.io
  groupPriorityMinimum: 16800
  version: v1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2023-11-16T20:16:04Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
