apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2023-11-16T20:16:04Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.node.k8s.io
  resourceVersion: "33"
  uid: fbc90691-b5d4-4b21-9928-87bf76b59c86
spec:
  group: node.k8s.io
  groupPriorityMinimum: 16300
  version: v1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2023-11-16T20:16:04Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
