apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"slate-controller-cr"},"rules":[{"apiGroups":["*"],"resources":["*"],"verbs":["*"]}]}
  creationTimestamp: "2023-11-17T18:54:43Z"
  name: slate-controller-cr
  resourceVersion: "156539"
  uid: 85fb4541-d34d-4343-99cb-a2d358f400db
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
