apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-11-16T20:16:07Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:ttl-controller
  resourceVersion: "178"
  uid: 18747dba-5a9e-4a97-acd5-9b8e32f63d2c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:ttl-controller
subjects:
- kind: ServiceAccount
  name: ttl-controller
  namespace: kube-system
