apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2023-11-16T20:16:10Z"
  name: kubeadm:node-proxier
  resourceVersion: "258"
  uid: 8617cebe-bdf7-4f45-abfa-b27da6c6ba21
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-proxier
subjects:
- kind: ServiceAccount
  name: kube-proxy
  namespace: kube-system
