apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"slate-controller-crb"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"slate-controller-cr"},"subjects":[{"kind":"ServiceAccount","name":"slate-controller-sa","namespace":"default"}]}
  creationTimestamp: "2023-11-17T18:54:43Z"
  name: slate-controller-crb
  resourceVersion: "156540"
  uid: a1544a3f-92af-4b53-995f-82dfaf9c6e89
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: slate-controller-cr
subjects:
- kind: ServiceAccount
  name: slate-controller-sa
  namespace: default
