apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-11-16T20:16:07Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:attachdetach-controller
  resourceVersion: "149"
  uid: 3261fd7c-0fe7-4959-ba27-23fc19f9e47a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:attachdetach-controller
subjects:
- kind: ServiceAccount
  name: attachdetach-controller
  namespace: kube-system
