apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-11-16T20:16:07Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:namespace-controller
  resourceVersion: "163"
  uid: 19cab50b-7c11-4864-a518-e0a8a6b3ab0e
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:namespace-controller
subjects:
- kind: ServiceAccount
  name: namespace-controller
  namespace: kube-system
