apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-11-16T20:16:07Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:node-controller
  resourceVersion: "164"
  uid: c8c1b814-e341-4adb-8a3c-d1532b0f1f1b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:node-controller
subjects:
- kind: ServiceAccount
  name: node-controller
  namespace: kube-system
