apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-11-16T20:16:07Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:endpoint-controller
  resourceVersion: "155"
  uid: ff723bcf-8891-4cb3-8baa-ea470f5569a6
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:endpoint-controller
subjects:
- kind: ServiceAccount
  name: endpoint-controller
  namespace: kube-system
