apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-11-16T20:16:06Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:monitoring
  resourceVersion: "138"
  uid: 29c1808e-907d-4a84-a5c3-fc03c20a4bc8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:monitoring
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:monitoring
