apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-11-16T20:16:07Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:persistent-volume-binder
  resourceVersion: "165"
  uid: 74428929-6de3-435e-84a0-afb216911cfd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:persistent-volume-binder
subjects:
- kind: ServiceAccount
  name: persistent-volume-binder
  namespace: kube-system
