apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTjFSbU9OcnBtd2N3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeE1UWXlNREV3TlRSYUZ3MHpNekV4TVRNeU1ERTFOVFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURUR0ZKMVkwTEhvQVpEUFlFVGlJVy81Q3BWUmxrZ2NVK00rQmwwUHNrTHI4d1M5WUtpVUtxdW53ekUKLzZjeWovTnppeDFVdkttRCtqL2IzS2hhK042eTRyMHdrV3lyYWYxZVFtSVdvMytqNnJpRDhJVXlUMklJWGtnLwpIRURRYlczTFl0bklzTmZDYzZvRWIrODVTblltZmFWM0hvVlpBclUzdzVqWnY3WGRQclBJS2MyWG82a0Q0a0trCnNiWjJlWjdtSkhGemhzeXZ4enhwSk91cUM3WVZ5S2NDdHVZck56NkhyeHBlbDJLdWJJQzJBM21aN3FNN1Q5MFQKVzNTSVkycVFxN3RSTm1udDdQWE80bWRzd2RnRFFocHlOVEozazhHR1FxTzFMajFxWkpTVTlGQ1JsdEtEY3dDYQprMCt5UzFpSWxpY1E4NjhiSE50d05qYlBHaTF0QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTc3NRcWRialpicE5meFp3TVpOMThuZ0hPK1FUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVFEWFhIcWtsbAorQWwyL3drWnFKdEt2MDRFRGZsYTc1UkZabDhtaEpuMlJGdU9XVXMyYlJ1aVBNZnppTUp3Z2p2RTVkN0QrVUdCCnFkS3ZveTl4YTM2dy9Cb0pOcVdDNUIzcVFXbExPUncxUGJJT082RFVqSjk2Qk01d1VxUUs3c01FTk1yWTQ2QkMKR2dyOEVQVjNSTUx2SXVvUk93NGovVmtGaFRYb3I4TmIwK3lmcWdtTzV2SEN2T2ZQTkN6WUVzdFJBY3MyK1Q0Ngp4K1NzUWlvcEY0blRGNGNvS3h2VFBwL2daRzFkREVUUytKclV3WkJJVWFBMmNGQnU5WER4T3Irb0k0VjllRXpICm9UMFBnalpmUHc4VmNWNUJKRlVFQm5JYlpOeVM2U045WS9sSmxUUzlOVGV3UHU3L2pReG5KYjhiVDZBS2Z1Si8KN1BTdXoxeFRFR05GCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://node0.gangmuk-178336.istio-pg0.clemson.cloudlab.us:6443
      name: ""
    contexts: null
    current-context: ""
    kind: Config
    preferences: {}
    users: null
kind: ConfigMap
metadata:
  creationTimestamp: "2023-11-16T20:16:09Z"
  name: cluster-info
  namespace: kube-public
  resourceVersion: "1745968"
  uid: 0d8e8f49-66db-4ac0-8640-ddc950ce2600
