apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBTCCAe2gAwIBAgIIN1RmONrpmwcwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczAeFw0yMzExMTYyMDEwNTRaFw0zMzExMTMyMDE1NTRaMBUx
    EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDTGFJ1Y0LHoAZDPYETiIW/5CpVRlkgcU+M+Bl0PskLr8wS9YKiUKqunwzE
    /6cyj/Nzix1UvKmD+j/b3Kha+N6y4r0wkWyraf1eQmIWo3+j6riD8IUyT2IIXkg/
    HEDQbW3LYtnIsNfCc6oEb+85SnYmfaV3HoVZArU3w5jZv7XdPrPIKc2Xo6kD4kKk
    sbZ2eZ7mJHFzhsyvxzxpJOuqC7YVyKcCtuYrNz6Hrxpel2KubIC2A3mZ7qM7T90T
    W3SIY2qQq7tRNmnt7PXO4mdswdgDQhpyNTJ3k8GGQqO1Lj1qZJSU9FCRltKDcwCa
    k0+yS1iIlicQ868bHNtwNjbPGi1tAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSssQqdbjZbpNfxZwMZN18ngHO+QTAV
    BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQAQDXXHqkll
    +Al2/wkZqJtKv04EDfla75RFZl8mhJn2RFuOWUs2bRuiPMfziMJwgjvE5d7D+UGB
    qdKvoy9xa36w/BoJNqWC5B3qQWlLORw1PbIOO6DUjJ96BM5wUqQK7sMENMrY46BC
    Ggr8EPV3RMLvIuoROw4j/VkFhTXor8Nb0+yfqgmO5vHCvOfPNCzYEstRAcs2+T46
    x+SsQiopF4nTF4coKxvTPp/gZG1dDETS+JrUwZBIUaA2cFBu9XDxOr+oI4V9eEzH
    oT0PgjZfPw8VcV5BJFUEBnIbZNyS6SN9Y/lJlTS9NTewPu7/jQxnJb8bT6AKfuJ/
    7PSuz1xTEGNF
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  creationTimestamp: "2023-11-16T20:16:21Z"
  name: kube-root-ca.crt
  namespace: default
  resourceVersion: "322"
  uid: 89e82579-2490-479b-89db-858c639796f8
