apiVersion: v1
data:
  since: "2023-11-16"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-11-16T20:16:04Z"
  name: kube-apiserver-legacy-service-account-token-tracking
  namespace: kube-system
  resourceVersion: "23"
  uid: 747a4043-65cb-4be1-874f-6e144d7f7e8f
