apiVersion: v1
data:
  root-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIC/DCCAeSgAwIBAgIQMVMxCC3x9RjmFVDo1S3TvjANBgkqhkiG9w0BAQsFADAY
    MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTIzMTExNjIzMTQ0OFoXDTMzMTEx
    MzIzMTQ0OFowGDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBAMaJDsWoFJSy77Qvm5uIdcb3yeC9CDw0JKXIDx8u
    JQPBw/k8F/U4kgIXgW6ZjnaGYHzLKf7TDoCKjdMGA8nXIphCMhTGRGgFI0ekkWQz
    pQ17JF0FxHj+BfYn0cfEn4zK52bduTay9XqjX6RTE9iwPE6AUIT+mFyA4fqB3Sce
    Y9QyLRR8y19f6j7nVwczwlr7vA87E03LUYCjw9sqY2tEz2RnMa6goBZpqdAjILmJ
    iL7LutPDBe71wlK5nzhMEoFElk86N89D7G7vEoq9vv+lSOWZ0AsKA9gs8HbMcqRy
    4DOU7Lf4uSMn+oZMX5Khzx/wQ2SkjB+p/ysZcLx09FrXGE8CAwEAAaNCMEAwDgYD
    VR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFJ6oSLpGBgdz
    +Kr40PHNxxq5jieLMA0GCSqGSIb3DQEBCwUAA4IBAQBwW1+DaEHl3OavTrDG1wtE
    Q8mQUBjnzlO4Z+iJTrFQEzRkheOxsf7ssbdccGDOZ4nvfUH9a7s0mLqcmYIc0M8D
    O0wqGuDkVUpu2TjrhgPrzM6hLkUjULS+KMkrmmGuNzV/PZpuV0Sd0wbohi+D7UTU
    AVhA4jTJgExK8VgX2+LaYGDEocwHmfWb04Y64XCNPpi0qTtggGfIf7rf9n7PsrQd
    oPRK94v8d+zDpRnWmJiqRPJE7EhlZLDU7nCsTWWryBB2McWWYHhg1PLAkWQI2veV
    haERZ57EmBcPTkV9y9PMzBAtsjH34QWGS7imZPHBU1FrzX5pkWk04SXyUU+515Co
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: "2023-11-17T20:43:26Z"
  labels:
    istio.io/config: "true"
  name: istio-ca-root-cert
  namespace: metallb-system
  resourceVersion: "170991"
  uid: c5b44bfa-e7ad-4665-8e44-08b7f0eae57b
