apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"slate-controller","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"slate-controller","version":"v1"}},"template":{"metadata":{"labels":{"app":"slate-controller","version":"v1"}},"spec":{"containers":[{"image":"ghcr.io/adiprerepa/slate-controller:latest","imagePullPolicy":"Always","name":"slate-controller","ports":[{"containerPort":8080}]}],"serviceAccountName":"slate-controller-sa","topologySpreadConstraints":[{"labelSelector":{"matchLabels":{"app":"slate-controller"}},"maxSkew":1,"topologyKey":"topology.kubernetes.io/zone","whenUnsatisfiable":"ScheduleAnyway"}]}}}}
  creationTimestamp: "2023-11-17T18:54:44Z"
  generation: 10
  name: slate-controller
  namespace: default
  resourceVersion: "2565416"
  uid: 5895ec2e-cf9a-4599-9537-e13c64d1f787
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: slate-controller
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-12-01T14:48:52-06:00"
      creationTimestamp: null
      labels:
        app: slate-controller
        version: v1
    spec:
      containers:
      - image: ghcr.io/adiprerepa/slate-controller:latest
        imagePullPolicy: Always
        name: slate-controller
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: slate-controller-sa
      serviceAccountName: slate-controller-sa
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: slate-controller
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-11-28T07:42:45Z"
    lastUpdateTime: "2023-11-28T07:42:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-17T18:54:44Z"
    lastUpdateTime: "2023-12-01T20:49:13Z"
    message: ReplicaSet "slate-controller-845f44cd47" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 10
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
