apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"slate-global-controller","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"slate-global-controller","version":"v1"}},"template":{"metadata":{"labels":{"app":"slate-global-controller","version":"v1"}},"spec":{"containers":[{"image":"ghcr.io/adiprerepa/slate-global-controller:latest","imagePullPolicy":"Always","name":"slate-global-controller","ports":[{"containerPort":8080}]}],"serviceAccountName":"slate-global-controller-sa"}}}}
  creationTimestamp: "2023-11-17T05:32:10Z"
  generation: 12
  name: slate-global-controller
  namespace: default
  resourceVersion: "2565256"
  uid: bd7cb0b7-468c-4968-8f82-a9ef9bb4101a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: slate-global-controller
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-12-01T14:48:52-06:00"
      creationTimestamp: null
      labels:
        app: slate-global-controller
        version: v1
    spec:
      containers:
      - image: ghcr.io/adiprerepa/slate-global-controller:latest
        imagePullPolicy: Always
        name: slate-global-controller
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: slate-global-controller-sa
      serviceAccountName: slate-global-controller-sa
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-11-28T06:06:55Z"
    lastUpdateTime: "2023-11-28T06:06:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-17T05:32:10Z"
    lastUpdateTime: "2023-12-01T20:49:04Z"
    message: ReplicaSet "slate-global-controller-679c45bcc6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 12
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
