addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.1.135
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: node1.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  targetRef:
    kind: Pod
    name: productpage-v1-7bd957446b-f5z45
    namespace: default
    uid: 35282263-fe74-4815-a82b-bbf508fd7376
  zone: us-west-1a
- addresses:
  - 10.244.2.56
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: node4.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  targetRef:
    kind: Pod
    name: productpage-v1-76f9d5fdb9-sgzsw
    namespace: default
    uid: 11a3099f-ae1e-419b-8c6f-1967fe3aff81
  zone: us-east-1a
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-12-01T20:53:03Z"
  creationTimestamp: "2023-11-16T21:02:35Z"
  generateName: productpage-
  generation: 100
  labels:
    app: productpage
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: productpage
    service: productpage
  name: productpage-v9rnb
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: productpage
    uid: f2a5a9d6-2ffc-42d1-a6a4-56d49cd3d226
  resourceVersion: "2566436"
  uid: 74f0163c-3eba-4e61-ba9c-1d3e12007a4d
ports:
- name: http
  port: 9080
  protocol: TCP
