apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-11-16T21:02:34Z"
  labels:
    app: details
    service: details
  name: details
  namespace: default
  resourceVersion: "2566365"
  uid: 9d227746-5de4-470f-a32e-100af5dedc1b
subsets:
- addresses:
  - ip: 10.244.1.137
    nodeName: node1.gangmuk-178336.istio-pg0.clemson.cloudlab.us
    targetRef:
      kind: Pod
      name: details-v1-749ffb45fc-77lc2
      namespace: default
      uid: ed8695af-e4b1-4767-8470-790ee7f10472
  - ip: 10.244.2.53
    nodeName: node4.gangmuk-178336.istio-pg0.clemson.cloudlab.us
    targetRef:
      kind: Pod
      name: details-v1-7d55956b94-br7h6
      namespace: default
      uid: d369daf9-5642-4cb7-af2e-3278885c67f8
  ports:
  - name: http
    port: 9080
    protocol: TCP
