apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-11-16T21:02:35Z"
  labels:
    app: productpage
    service: productpage
  name: productpage
  namespace: default
  resourceVersion: "2566397"
  uid: eadc80bb-b7c7-4906-bd96-bc295de8e021
subsets:
- addresses:
  - ip: 10.244.1.135
    nodeName: node1.gangmuk-178336.istio-pg0.clemson.cloudlab.us
    targetRef:
      kind: Pod
      name: productpage-v1-7bd957446b-f5z45
      namespace: default
      uid: 35282263-fe74-4815-a82b-bbf508fd7376
  - ip: 10.244.2.56
    nodeName: node4.gangmuk-178336.istio-pg0.clemson.cloudlab.us
    targetRef:
      kind: Pod
      name: productpage-v1-76f9d5fdb9-sgzsw
      namespace: default
      uid: 11a3099f-ae1e-419b-8c6f-1967fe3aff81
  ports:
  - name: http
    port: 9080
    protocol: TCP
