apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-11-16T23:17:55Z"
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.20.0
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
  resourceVersion: "2566711"
  uid: 5baf2360-9ea5-41f2-8cf1-590590b41dc5
subsets:
- addresses:
  - ip: 10.244.1.126
    nodeName: node1.gangmuk-178336.istio-pg0.clemson.cloudlab.us
    targetRef:
      kind: Pod
      name: istio-ingressgateway-775b47bdf7-qcx8l
      namespace: istio-system
      uid: 37a87bbf-37f8-4655-8481-ed974354afda
  - ip: 10.244.2.57
    nodeName: node4.gangmuk-178336.istio-pg0.clemson.cloudlab.us
    targetRef:
      kind: Pod
      name: istio-ingressgateway-685595db7d-qg2qv
      namespace: istio-system
      uid: 2ae4a0ad-6c18-448e-aaf7-366a3b9649b3
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
  - name: http2
    port: 8080
    protocol: TCP
  - name: https
    port: 8443
    protocol: TCP
