addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.2.45
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: node4.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  targetRef:
    kind: Pod
    name: istio-eastwestgateway-7bff646454-lzhsm
    namespace: istio-system
    uid: df5e9f76-b19c-4663-80ba-0733469a528c
  zone: us-east-1a
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-12-01T20:43:08Z"
  creationTimestamp: "2023-11-16T21:22:19Z"
  generateName: istio-eastwestgateway-
  generation: 9
  labels:
    app: istio-eastwestgateway
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    install.operator.istio.io/owning-resource: installed-state-eastwest
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: eastwestgateway
    istio.io/rev: default
    kubernetes.io/service-name: istio-eastwestgateway
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.20.0
    release: istio
    topology.istio.io/network: network1
  name: istio-eastwestgateway-bkb7k
  namespace: istio-system
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: istio-eastwestgateway
    uid: 9604d279-c55b-4ceb-8793-e31502cf9212
  resourceVersion: "2564125"
  uid: 2db7aab2-338b-41a0-a928-291993946f6b
ports:
- name: tls-webhook
  port: 15017
  protocol: TCP
- name: tls-istiod
  port: 15012
  protocol: TCP
- name: tls
  port: 15443
  protocol: TCP
- name: status-port
  port: 15021
  protocol: TCP
