addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.1.126
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: node1.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  targetRef:
    kind: Pod
    name: istio-ingressgateway-775b47bdf7-qcx8l
    namespace: istio-system
    uid: 37a87bbf-37f8-4655-8481-ed974354afda
  zone: us-west-1a
- addresses:
  - 10.244.2.57
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: node4.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  targetRef:
    kind: Pod
    name: istio-ingressgateway-685595db7d-qg2qv
    namespace: istio-system
    uid: 2ae4a0ad-6c18-448e-aaf7-366a3b9649b3
  zone: us-east-1a
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-12-01T20:55:00Z"
  creationTimestamp: "2023-11-16T23:17:55Z"
  generateName: istio-ingressgateway-
  generation: 44
  labels:
    app: istio-ingressgateway
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    kubernetes.io/service-name: istio-ingressgateway
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.20.0
    release: istio
  name: istio-ingressgateway-54xqc
  namespace: istio-system
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: istio-ingressgateway
    uid: 940ee3d3-4e1a-42de-ab3c-974cfe646c79
  resourceVersion: "2566732"
  uid: e9ccaf3e-2513-4b6d-a1e2-62a8431dbbca
ports:
- name: http2
  port: 8080
  protocol: TCP
- name: https
  port: 8443
  protocol: TCP
- name: status-port
  port: 15021
  protocol: TCP
