apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-11-16T21:13:04Z"
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: pilot
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.20.0
    release: istio
  name: istiod
  namespace: istio-system
  resourceVersion: "2564108"
  uid: 3dd07f5a-3a6b-4541-9844-bf955ab35cd8
subsets:
- addresses:
  - ip: 10.244.2.46
    nodeName: node4.gangmuk-178336.istio-pg0.clemson.cloudlab.us
    targetRef:
      kind: Pod
      name: istiod-586b5556b7-pcgkp
      namespace: istio-system
      uid: df4635d3-aced-431e-b8a1-9d6f4b7bf341
  ports:
  - name: https-dns
    port: 15012
    protocol: TCP
  - name: grpc-xds
    port: 15010
    protocol: TCP
  - name: https-webhook
    port: 15017
    protocol: TCP
  - name: http-monitoring
    port: 15014
    protocol: TCP
