addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.0.4
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: node0.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  targetRef:
    kind: Pod
    name: coredns-5dd5756b68-b5ld5
    namespace: kube-system
    uid: 132702db-1b0d-42ed-8402-8cac0d8f05d9
- addresses:
  - 10.244.0.5
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: node0.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  targetRef:
    kind: Pod
    name: coredns-5dd5756b68-t8ft2
    namespace: kube-system
    uid: 8585986b-f8a2-4cf8-9aea-beea87bc0d23
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-11-16T20:16:24Z"
  creationTimestamp: "2023-11-16T20:16:22Z"
  generateName: kube-dns-
  generation: 4
  labels:
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
    kubernetes.io/service-name: kube-dns
  name: kube-dns-78jg8
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: kube-dns
    uid: 68b29e00-e925-4e3a-b5b0-6ee09f98ccc0
  resourceVersion: "382"
  uid: e8c97257-937b-4753-8caa-b468e89cf2d6
ports:
- name: metrics
  port: 9153
  protocol: TCP
- name: dns
  port: 53
  protocol: UDP
- name: dns-tcp
  port: 53
  protocol: TCP
