apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-11-16T21:22:19Z"
  labels:
    app: istio-eastwestgateway
    install.operator.istio.io/owning-resource: installed-state-eastwest
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: eastwestgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.20.0
    release: istio
    topology.istio.io/network: network1
  name: istio-eastwestgateway
  namespace: istio-system
  resourceVersion: "2564074"
  uid: c3d0bbd9-14f8-49ee-afeb-5a8f0e852e11
subsets:
- addresses:
  - ip: 10.244.2.45
    nodeName: node4.gangmuk-178336.istio-pg0.clemson.cloudlab.us
    targetRef:
      kind: Pod
      name: istio-eastwestgateway-7bff646454-lzhsm
      namespace: istio-system
      uid: df5e9f76-b19c-4663-80ba-0733469a528c
  ports:
  - name: tls
    port: 15443
    protocol: TCP
  - name: status-port
    port: 15021
    protocol: TCP
  - name: tls-istiod
    port: 15012
    protocol: TCP
  - name: tls-webhook
    port: 15017
    protocol: TCP
