apiVersion: v1
count: 291
eventTime: null
firstTimestamp: "2023-12-01T20:52:52Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: ratings-v1-564f9f5c69-578j2
  namespace: default
  resourceVersion: "2566290"
  uid: c0b9fd8d-82e9-4ff4-947d-0f901285de99
kind: Event
lastTimestamp: "2023-12-02T20:50:05Z"
message: '0/3 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane:
  }, 2 node(s) didn''t match pod topology spread constraints. preemption: 0/3 nodes
  are available: 1 Preemption is not helpful for scheduling, 2 No preemption victims
  found for incoming pod..'
metadata:
  creationTimestamp: "2023-12-01T20:52:52Z"
  name: ratings-v1-564f9f5c69-578j2.179cd077c5afd7ed
  namespace: default
  resourceVersion: "2743517"
  uid: bed7a1a7-9b64-4e26-b80a-75554ee609af
reason: FailedScheduling
reportingComponent: default-scheduler
reportingInstance: ""
source:
  component: default-scheduler
type: Warning
