apiVersion: flowcontrol.apiserver.k8s.io/v1beta3
kind: FlowSchema
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2023-11-16T20:16:05Z"
  generation: 1
  name: catch-all
  resourceVersion: "73"
  uid: d147b636-920a-42bb-9f55-e36b8c406438
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 10000
  priorityLevelConfiguration:
    name: catch-all
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    resourceRules:
    - apiGroups:
      - '*'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
    - group:
        name: system:unauthenticated
      kind: Group
    - group:
        name: system:authenticated
      kind: Group
status:
  conditions:
  - lastTransitionTime: "2023-11-16T20:16:05Z"
    message: This FlowSchema references the PriorityLevelConfiguration object named
      "catch-all" and it exists
    reason: Found
    status: "False"
    type: Dangling
