apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2023-11-16T20:16:04Z"
  labels:
    apiserver.kubernetes.io/identity: kube-apiserver
    kubernetes.io/hostname: node0.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  name: apiserver-d7wp3nwfrzdh4uaztzw722n4wi
  namespace: kube-system
  resourceVersion: "2744068"
  uid: c9472f2f-996d-4d2c-92fb-62df496d7f5e
spec:
  holderIdentity: apiserver-d7wp3nwfrzdh4uaztzw722n4wi_9ab13abb-aebe-43d6-907b-4064108552e5
  leaseDurationSeconds: 3600
  renewTime: "2023-12-02T20:54:33.381594Z"
