apiVersion: v1
kind: Node
metadata:
  annotations:
    flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"0e:4e:e8:9b:f9:60"}'
    flannel.alpha.coreos.com/backend-type: vxlan
    flannel.alpha.coreos.com/kube-subnet-manager: "true"
    flannel.alpha.coreos.com/public-ip: 130.127.133.123
    kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2023-11-26T05:35:03Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: node4.gangmuk-178336.istio-pg0.clemson.cloudlab.us
    kubernetes.io/os: linux
    topology.kubernetes.io/region: us-east-1
    topology.kubernetes.io/zone: us-east-1a
  name: node4.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  resourceVersion: "2743841"
  uid: 44f3cd9a-4060-4dd0-a07e-0b787389c666
spec:
  podCIDR: 10.244.2.0/24
  podCIDRs:
  - 10.244.2.0/24
status:
  addresses:
  - address: 130.127.133.123
    type: InternalIP
  - address: node4.gangmuk-178336.istio-pg0.clemson.cloudlab.us
    type: Hostname
  allocatable:
    cpu: "56"
    ephemeral-storage: "60345081347"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 263907448Ki
    pods: "110"
  capacity:
    cpu: "56"
    ephemeral-storage: 65478604Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 264009848Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2023-11-26T05:35:29Z"
    lastTransitionTime: "2023-11-26T05:35:29Z"
    message: Flannel is running on this node
    reason: FlannelIsUp
    status: "False"
    type: NetworkUnavailable
  - lastHeartbeatTime: "2023-12-02T20:52:41Z"
    lastTransitionTime: "2023-11-26T05:35:03Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2023-12-02T20:52:41Z"
    lastTransitionTime: "2023-11-26T05:35:03Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2023-12-02T20:52:41Z"
    lastTransitionTime: "2023-11-26T05:35:03Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2023-12-02T20:52:41Z"
    lastTransitionTime: "2023-11-26T05:35:26Z"
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - docker.io/istio/examples-bookinfo-reviews-v3@sha256:a79a7512a128a47051cee3088339a33221b3ce13ea6e3ae86b8ab11c061be72c
    - docker.io/istio/examples-bookinfo-reviews-v3:1.18.0
    sizeBytes: 415288108
  - names:
    - ghcr.io/adiprerepa/slate-controller@sha256:80d5967f857c22994a7a2acdf8582c64d4c55972ecdbc56579af87b22db16254
    - ghcr.io/adiprerepa/slate-controller:latest
    sizeBytes: 344377294
  - names:
    - docker.io/istio/proxyv2@sha256:19e8ca96e4f46733a3377fa962cb88cad13a35afddb9139ff795e36237327137
    - docker.io/istio/proxyv2:1.20.0
    sizeBytes: 96408950
  - names:
    - docker.io/istio/examples-bookinfo-ratings-v1@sha256:93e8d6f8a7eeac079ef5724d4b20cbc15afcdacb71c8c1402ea1eba0ec0bd86e
    - docker.io/istio/examples-bookinfo-ratings-v1:1.18.0
    sizeBytes: 83993197
  - names:
    - docker.io/istio/pilot@sha256:da619cc0915a27988ba8357916d84b4a137253a9df967e6521b14dc7100bb246
    - docker.io/istio/pilot:1.20.0
    sizeBytes: 74042223
  - names:
    - docker.io/istio/examples-bookinfo-productpage-v1@sha256:e2723a59bde95d630ed96630af25058ebea255219161d6a8ac6c25d67d7e1b5a
    - docker.io/istio/examples-bookinfo-productpage-v1:1.18.0
    sizeBytes: 67867892
  - names:
    - docker.io/istio/examples-bookinfo-details-v1@sha256:daa08c3652d3c1f924988cd0e6dcb2973d7ea9090e2088418e442c87bbfd7091
    - docker.io/istio/examples-bookinfo-details-v1:1.18.0
    sizeBytes: 62493667
  - names:
    - quay.io/metallb/speaker@sha256:b4a5576a3cf5816612f54355804bdb83a2560ad4120691129a2e5bac5339ee0c
    - quay.io/metallb/speaker:v0.13.12
    sizeBytes: 52067123
  - names:
    - docker.io/flannel/flannel@sha256:34585231b69718efc4f926ebca734659f01221554f37a925d9a1190bb16e5b91
    - docker.io/flannel/flannel:v0.22.3
    sizeBytes: 27017673
  - names:
    - registry.k8s.io/kube-proxy@sha256:e63408a0f5068a7e9d4b34fd72b4a2b0e5512509b53cd2123a37fc991b0ef532
    - registry.k8s.io/kube-proxy:v1.28.4
    sizeBytes: 24581402
  - names:
    - docker.io/flannel/flannel-cni-plugin@sha256:ca6779c6ad63b77af8a00151cefc08578241197b9a6fe144b0e55484bc52b852
    - docker.io/flannel/flannel-cni-plugin:v1.2.0
    sizeBytes: 3879095
  - names:
    - registry.k8s.io/pause@sha256:7031c1b283388d2c2e09b57badb803c05ebed362dc88d84b480cc47f72a21097
    - registry.k8s.io/pause:3.9
    sizeBytes: 321520
  nodeInfo:
    architecture: amd64
    bootID: 0870d5a4-bcc5-4ae4-ab7a-c869ec915a86
    containerRuntimeVersion: containerd://1.6.25
    kernelVersion: 5.15.0-86-generic
    kubeProxyVersion: v1.28.2
    kubeletVersion: v1.28.2
    machineID: b8de976186d345a9813f07134500eb0a
    operatingSystem: linux
    osImage: Ubuntu 22.04.3 LTS
    systemUUID: 4c4c4544-0059-3010-8035-c3c04f333832
