apiVersion: v1
kind: Node
metadata:
  annotations:
    flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"92:4a:78:41:bf:90"}'
    flannel.alpha.coreos.com/backend-type: vxlan
    flannel.alpha.coreos.com/kube-subnet-manager: "true"
    flannel.alpha.coreos.com/public-ip: 130.127.133.109
    kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2023-11-16T20:16:04Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: node0.gangmuk-178336.istio-pg0.clemson.cloudlab.us
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: ""
    node.kubernetes.io/exclude-from-external-load-balancers: ""
  name: node0.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  resourceVersion: "2743554"
  uid: 551aebc2-bff0-4b90-a906-398203845761
spec:
  podCIDR: 10.244.0.0/24
  podCIDRs:
  - 10.244.0.0/24
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
status:
  addresses:
  - address: 130.127.133.109
    type: InternalIP
  - address: node0.gangmuk-178336.istio-pg0.clemson.cloudlab.us
    type: Hostname
  allocatable:
    cpu: "56"
    ephemeral-storage: "60345081347"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 263907456Ki
    pods: "110"
  capacity:
    cpu: "56"
    ephemeral-storage: 65478604Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 264009856Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2023-11-16T20:18:38Z"
    lastTransitionTime: "2023-11-16T20:18:38Z"
    message: Flannel is running on this node
    reason: FlannelIsUp
    status: "False"
    type: NetworkUnavailable
  - lastHeartbeatTime: "2023-12-02T20:50:18Z"
    lastTransitionTime: "2023-11-16T20:16:03Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2023-12-02T20:50:18Z"
    lastTransitionTime: "2023-11-16T20:16:03Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2023-12-02T20:50:18Z"
    lastTransitionTime: "2023-11-16T20:16:03Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2023-12-02T20:50:18Z"
    lastTransitionTime: "2023-11-16T20:16:04Z"
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - registry.k8s.io/etcd@sha256:e013d0d5e4e25d00c61a7ff839927a1f36479678f11e49502b53a5e0b14f10c3
    - registry.k8s.io/etcd:3.5.9-0
    sizeBytes: 102894559
  - names:
    - quay.io/metallb/speaker@sha256:b4a5576a3cf5816612f54355804bdb83a2560ad4120691129a2e5bac5339ee0c
    - quay.io/metallb/speaker:v0.13.12
    sizeBytes: 52067123
  - names:
    - registry.k8s.io/kube-apiserver@sha256:5b28a364467cf7e134343bb3ee2c6d40682b473a743a72142c7bbe25767d36eb
    - registry.k8s.io/kube-apiserver:v1.28.4
    sizeBytes: 34683820
  - names:
    - registry.k8s.io/kube-apiserver@sha256:8db46adefb0f251da210504e2ce268c36a5a7c630667418ea4601f63c9057a2d
    - registry.k8s.io/kube-apiserver:v1.28.3
    sizeBytes: 34666616
  - names:
    - registry.k8s.io/kube-controller-manager@sha256:65486c8c338f96dc022dd1a0abe8763e38f35095b84b208c78f44d9e99447d1c
    - registry.k8s.io/kube-controller-manager:v1.28.4
    sizeBytes: 33420443
  - names:
    - registry.k8s.io/kube-controller-manager@sha256:640661231facded984f698e79315bceb5391b04e5159662e940e6e5ab2098707
    - registry.k8s.io/kube-controller-manager:v1.28.3
    sizeBytes: 33404036
  - names:
    - docker.io/flannel/flannel@sha256:34585231b69718efc4f926ebca734659f01221554f37a925d9a1190bb16e5b91
    - docker.io/flannel/flannel:v0.22.3
    sizeBytes: 27017673
  - names:
    - registry.k8s.io/kube-proxy@sha256:e63408a0f5068a7e9d4b34fd72b4a2b0e5512509b53cd2123a37fc991b0ef532
    - registry.k8s.io/kube-proxy:v1.28.4
    sizeBytes: 24581402
  - names:
    - registry.k8s.io/kube-proxy@sha256:73a9f275e1fa5f0b9ae744914764847c2c4fdc66e9e528d67dea70007f9a6072
    - registry.k8s.io/kube-proxy:v1.28.3
    sizeBytes: 24561096
  - names:
    - registry.k8s.io/kube-scheduler@sha256:335bba9e861b88fa8b7bb9250bcd69b7a33f83da4fee93f9fc0eedc6f34e28ba
    - registry.k8s.io/kube-scheduler:v1.28.4
    sizeBytes: 18834488
  - names:
    - registry.k8s.io/kube-scheduler@sha256:2cfaab2fe5e5937bc37f3d05f3eb7a4912a981ab8375f1d9c2c3190b259d1725
    - registry.k8s.io/kube-scheduler:v1.28.3
    sizeBytes: 18815674
  - names:
    - registry.k8s.io/coredns/coredns@sha256:a0ead06651cf580044aeb0a0feba63591858fb2e43ade8c9dea45a6a89ae7e5e
    - registry.k8s.io/coredns/coredns:v1.10.1
    sizeBytes: 16190758
  - names:
    - docker.io/flannel/flannel-cni-plugin@sha256:ca6779c6ad63b77af8a00151cefc08578241197b9a6fe144b0e55484bc52b852
    - docker.io/flannel/flannel-cni-plugin:v1.2.0
    sizeBytes: 3879095
  - names:
    - registry.k8s.io/pause@sha256:7031c1b283388d2c2e09b57badb803c05ebed362dc88d84b480cc47f72a21097
    - registry.k8s.io/pause:3.9
    sizeBytes: 321520
  nodeInfo:
    architecture: amd64
    bootID: ab256c15-56fb-4350-8a46-3e0028a59e9a
    containerRuntimeVersion: containerd://1.6.24
    kernelVersion: 5.15.0-86-generic
    kubeProxyVersion: v1.28.2
    kubeletVersion: v1.28.2
    machineID: 39a547887d684c0bb02c427a1e5167dd
    operatingSystem: linux
    osImage: Ubuntu 22.04.3 LTS
    systemUUID: 4c4c4544-0059-3010-8042-c3c04f333832
