apiVersion: v1
kind: Pod
metadata:
  annotations:
    ambient.istio.io/redirection: disabled
    kubectl.kubernetes.io/restartedAt: "2023-12-01T14:42:58-06:00"
    prometheus.io/port: "15014"
    prometheus.io/scrape: "true"
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2023-12-01T20:42:58Z"
  generateName: istiod-586b5556b7-
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: unknown
    istio: pilot
    istio.io/rev: default
    operator.istio.io/component: Pilot
    pod-template-hash: 586b5556b7
    sidecar.istio.io/inject: "false"
  name: istiod-586b5556b7-pcgkp
  namespace: istio-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: istiod-586b5556b7
    uid: 32e55820-11c9-410a-99a4-1604fe7ea8e3
  resourceVersion: "2564098"
  uid: df4635d3-aced-431e-b8a1-9d6f4b7bf341
spec:
  containers:
  - args:
    - discovery
    - --monitoringAddr=:15014
    - --log_output_level=default:info
    - --domain
    - cluster.local
    - --keepaliveMaxServerConnectionAge
    - 30m
    env:
    - name: REVISION
      value: default
    - name: JWT_POLICY
      value: third-party-jwt
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: KUBECONFIG
      value: /var/run/secrets/remote/config
    - name: PILOT_TRACE_SAMPLING
      value: "1"
    - name: PILOT_ENABLE_ANALYSIS
      value: "false"
    - name: CLUSTER_ID
      value: cluster1
    - name: GOMEMLIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: limits.memory
    - name: GOMAXPROCS
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: limits.cpu
    - name: PLATFORM
    image: docker.io/istio/pilot:1.20.0
    imagePullPolicy: IfNotPresent
    name: discovery
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 15010
      protocol: TCP
    - containerPort: 15017
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: istio-token
      readOnly: true
    - mountPath: /var/run/secrets/istio-dns
      name: local-certs
    - mountPath: /etc/cacerts
      name: cacerts
      readOnly: true
    - mountPath: /var/run/secrets/remote
      name: istio-kubeconfig
      readOnly: true
    - mountPath: /var/run/secrets/istiod/tls
      name: istio-csr-dns-cert
      readOnly: true
    - mountPath: /var/run/secrets/istiod/ca
      name: istio-csr-ca-configmap
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-n9pvp
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node4.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: istiod
  serviceAccountName: istiod
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir:
      medium: Memory
    name: local-certs
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
  - name: cacerts
    secret:
      defaultMode: 420
      optional: true
      secretName: cacerts
  - name: istio-kubeconfig
    secret:
      defaultMode: 420
      optional: true
      secretName: istio-kubeconfig
  - name: istio-csr-dns-cert
    secret:
      defaultMode: 420
      optional: true
      secretName: istiod-tls
  - configMap:
      defaultMode: 420
      name: istio-ca-root-cert
      optional: true
    name: istio-csr-ca-configmap
  - name: kube-api-access-n9pvp
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-12-01T20:42:59Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-12-01T20:43:06Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-12-01T20:43:06Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-12-01T20:42:59Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://3660d84d3ac1570b895f0faf69b6dea563a89673f5d9c9b92bf6959f0f90f749
    image: docker.io/istio/pilot:1.20.0
    imageID: docker.io/istio/pilot@sha256:da619cc0915a27988ba8357916d84b4a137253a9df967e6521b14dc7100bb246
    lastState: {}
    name: discovery
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-12-01T20:43:05Z"
  hostIP: 130.127.133.123
  phase: Running
  podIP: 10.244.2.46
  podIPs:
  - ip: 10.244.2.46
  qosClass: Burstable
  startTime: "2023-12-01T20:42:59Z"
