apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-11-16T23:13:32Z"
  generateName: kube-flannel-ds-
  labels:
    app: flannel
    controller-revision-hash: 6fbbc5c975
    pod-template-generation: "1"
    tier: node
  name: kube-flannel-ds-t7h7l
  namespace: kube-flannel
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: kube-flannel-ds
    uid: e8d16249-4ce1-44ba-af74-e2ce4c8e6716
  resourceVersion: "15029"
  uid: 7286dc60-6035-44c9-b4d4-483777c1f22d
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - node1.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  containers:
  - args:
    - --ip-masq
    - --kube-subnet-mgr
    command:
    - /opt/bin/flanneld
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: EVENT_QUEUE_DEPTH
      value: "5000"
    image: docker.io/flannel/flannel:v0.22.3
    imagePullPolicy: IfNotPresent
    name: kube-flannel
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
      privileged: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /run/flannel
      name: run
    - mountPath: /etc/kube-flannel/
      name: flannel-cfg
    - mountPath: /run/xtables.lock
      name: xtables-lock
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-m6r62
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  initContainers:
  - args:
    - -f
    - /flannel
    - /opt/cni/bin/flannel
    command:
    - cp
    image: docker.io/flannel/flannel-cni-plugin:v1.2.0
    imagePullPolicy: IfNotPresent
    name: install-cni-plugin
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/cni/bin
      name: cni-plugin
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-m6r62
      readOnly: true
  - args:
    - -f
    - /etc/kube-flannel/cni-conf.json
    - /etc/cni/net.d/10-flannel.conflist
    command:
    - cp
    image: docker.io/flannel/flannel:v0.22.3
    imagePullPolicy: IfNotPresent
    name: install-cni
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/cni/net.d
      name: cni
    - mountPath: /etc/kube-flannel/
      name: flannel-cfg
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-m6r62
      readOnly: true
  nodeName: node1.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: flannel
  serviceAccountName: flannel
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /run/flannel
      type: ""
    name: run
  - hostPath:
      path: /opt/cni/bin
      type: ""
    name: cni-plugin
  - hostPath:
      path: /etc/cni/net.d
      type: ""
    name: cni
  - configMap:
      defaultMode: 420
      name: kube-flannel-cfg
    name: flannel-cfg
  - hostPath:
      path: /run/xtables.lock
      type: FileOrCreate
    name: xtables-lock
  - name: kube-api-access-m6r62
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-11-16T23:13:57Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-11-16T23:13:59Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-11-16T23:13:59Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-11-16T23:13:32Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://ddbf858eaddd832fe41fac6f950447efbf0b926239283e1798826a7bae8a4890
    image: docker.io/flannel/flannel:v0.22.3
    imageID: docker.io/flannel/flannel@sha256:34585231b69718efc4f926ebca734659f01221554f37a925d9a1190bb16e5b91
    lastState: {}
    name: kube-flannel
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-11-16T23:13:58Z"
  hostIP: 130.127.133.111
  initContainerStatuses:
  - containerID: containerd://42274c4d2d0841fefe03cbe274811aa7cc42297c1fae1dd61c6faf9b0138caee
    image: docker.io/flannel/flannel-cni-plugin:v1.2.0
    imageID: docker.io/flannel/flannel-cni-plugin@sha256:ca6779c6ad63b77af8a00151cefc08578241197b9a6fe144b0e55484bc52b852
    lastState: {}
    name: install-cni-plugin
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://42274c4d2d0841fefe03cbe274811aa7cc42297c1fae1dd61c6faf9b0138caee
        exitCode: 0
        finishedAt: "2023-11-16T23:13:47Z"
        reason: Completed
        startedAt: "2023-11-16T23:13:47Z"
  - containerID: containerd://a1fc2a8bdebb3741c44de1c6c8b49982ff1b1ab09eac947a7f6c5c668e9cd3f7
    image: docker.io/flannel/flannel:v0.22.3
    imageID: docker.io/flannel/flannel@sha256:34585231b69718efc4f926ebca734659f01221554f37a925d9a1190bb16e5b91
    lastState: {}
    name: install-cni
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://a1fc2a8bdebb3741c44de1c6c8b49982ff1b1ab09eac947a7f6c5c668e9cd3f7
        exitCode: 0
        finishedAt: "2023-11-16T23:13:55Z"
        reason: Completed
        startedAt: "2023-11-16T23:13:55Z"
  phase: Running
  podIP: 130.127.133.111
  podIPs:
  - ip: 130.127.133.111
  qosClass: Burstable
  startTime: "2023-11-16T23:13:32Z"
