apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: e80959db9eb8bca881607444583db1f4
    kubernetes.io/config.mirror: e80959db9eb8bca881607444583db1f4
    kubernetes.io/config.seen: "2023-11-16T20:16:10.418431175Z"
    kubernetes.io/config.source: file
  creationTimestamp: "2023-11-16T20:16:10Z"
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler-node0.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Node
    name: node0.gangmuk-178336.istio-pg0.clemson.cloudlab.us
    uid: 551aebc2-bff0-4b90-a906-398203845761
  resourceVersion: "313"
  uid: a15c3e32-7acc-409d-a097-580ce565bb72
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    image: registry.k8s.io/kube-scheduler:v1.28.4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: node0.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-11-16T20:16:10Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-11-16T20:16:21Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-11-16T20:16:21Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-11-16T20:16:10Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://4b1d9f05670404b464ae64c6c6100f2ef5633af8a45fbd5f2af94268dd284315
    image: registry.k8s.io/kube-scheduler:v1.28.4
    imageID: registry.k8s.io/kube-scheduler@sha256:335bba9e861b88fa8b7bb9250bcd69b7a33f83da4fee93f9fc0eedc6f34e28ba
    lastState: {}
    name: kube-scheduler
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-11-16T20:16:01Z"
  hostIP: 130.127.133.109
  phase: Running
  podIP: 130.127.133.109
  podIPs:
  - ip: 130.127.133.109
  qosClass: Burstable
  startTime: "2023-11-16T20:16:10Z"
