apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/port: "7472"
    prometheus.io/scrape: "true"
  creationTimestamp: "2023-11-17T20:43:28Z"
  generateName: speaker-
  labels:
    app: metallb
    component: speaker
    controller-revision-hash: 6d4487bcfb
    pod-template-generation: "1"
  name: speaker-9t2nc
  namespace: metallb-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: speaker
    uid: 9d1b9705-6f0f-4669-ab14-251f2ca9df99
  resourceVersion: "171147"
  uid: 7f8d6266-8fdc-4310-bb57-3172aa519eb2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - node0.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  containers:
  - args:
    - --port=7472
    - --log-level=info
    env:
    - name: METALLB_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: METALLB_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: METALLB_ML_BIND_ADDR
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: METALLB_ML_LABELS
      value: app=metallb,component=speaker
    - name: METALLB_ML_SECRET_KEY_PATH
      value: /etc/ml_secret_key
    image: quay.io/metallb/speaker:v0.13.12
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: monitoring
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: speaker
    ports:
    - containerPort: 7472
      hostPort: 7472
      name: monitoring
      protocol: TCP
    - containerPort: 7946
      hostPort: 7946
      name: memberlist-tcp
      protocol: TCP
    - containerPort: 7946
      hostPort: 7946
      name: memberlist-udp
      protocol: UDP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: monitoring
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_RAW
        drop:
        - ALL
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/ml_secret_key
      name: memberlist
      readOnly: true
    - mountPath: /etc/metallb
      name: metallb-excludel2
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-98tlk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: node0.gangmuk-178336.istio-pg0.clemson.cloudlab.us
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: speaker
  serviceAccountName: speaker
  terminationGracePeriodSeconds: 2
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - name: memberlist
    secret:
      defaultMode: 420
      secretName: memberlist
  - configMap:
      defaultMode: 256
      name: metallb-excludel2
    name: metallb-excludel2
  - name: kube-api-access-98tlk
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-11-17T20:43:28Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-11-17T20:43:50Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-11-17T20:43:50Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-11-17T20:43:28Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://a63275cfadd2bf7165d711aad93101162451b1a89abbd91b0dfa75ae6d6b274f
    image: quay.io/metallb/speaker:v0.13.12
    imageID: quay.io/metallb/speaker@sha256:b4a5576a3cf5816612f54355804bdb83a2560ad4120691129a2e5bac5339ee0c
    lastState: {}
    name: speaker
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-11-17T20:43:31Z"
  hostIP: 130.127.133.109
  phase: Running
  podIP: 130.127.133.109
  podIPs:
  - ip: 130.127.133.109
  qosClass: BestEffort
  startTime: "2023-11-17T20:43:28Z"
