apiVersion: flowcontrol.apiserver.k8s.io/v1beta3
kind: PriorityLevelConfiguration
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2023-11-16T20:16:05Z"
  generation: 1
  name: exempt
  resourceVersion: "65"
  uid: da855b77-9d99-446e-86ae-ac54fd3d85fe
spec:
  exempt:
    lendablePercent: 0
    nominalConcurrencyShares: 0
  type: Exempt
status: {}
