apiVersion: flowcontrol.apiserver.k8s.io/v1beta3
kind: PriorityLevelConfiguration
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2023-11-16T20:16:04Z"
  generation: 1
  name: catch-all
  resourceVersion: "63"
  uid: 463d0320-567d-43cb-bb60-d6c9f10c97f2
spec:
  limited:
    lendablePercent: 0
    limitResponse:
      type: Reject
    nominalConcurrencyShares: 5
  type: Limited
status: {}
