apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "2"
    deployment.kubernetes.io/max-replicas: "3"
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: "2023-12-01T20:48:52Z"
  generation: 2
  labels:
    app: slate-controller
    pod-template-hash: 845f44cd47
    version: v1
  name: slate-controller-845f44cd47
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: slate-controller
    uid: 5895ec2e-cf9a-4599-9537-e13c64d1f787
  resourceVersion: "2565403"
  uid: 1524962f-3e07-4e67-8acc-ee77cd29a0e9
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slate-controller
      pod-template-hash: 845f44cd47
      version: v1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-12-01T14:48:52-06:00"
      creationTimestamp: null
      labels:
        app: slate-controller
        pod-template-hash: 845f44cd47
        version: v1
    spec:
      containers:
      - image: ghcr.io/adiprerepa/slate-controller:latest
        imagePullPolicy: Always
        name: slate-controller
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: slate-controller-sa
      serviceAccountName: slate-controller-sa
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: slate-controller
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
status:
  availableReplicas: 2
  fullyLabeledReplicas: 2
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
