apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "7"
  creationTimestamp: "2023-11-28T07:38:25Z"
  generation: 2
  labels:
    app: slate-controller
    pod-template-hash: bc9dbf586
    version: v1
  name: slate-controller-bc9dbf586
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: slate-controller
    uid: 5895ec2e-cf9a-4599-9537-e13c64d1f787
  resourceVersion: "1940113"
  uid: 7da4714c-6b15-4420-9666-faec7d3756d5
spec:
  replicas: 0
  selector:
    matchLabels:
      app: slate-controller
      pod-template-hash: bc9dbf586
      version: v1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-11-28T01:33:04-06:00"
      creationTimestamp: null
      labels:
        app: slate-controller
        pod-template-hash: bc9dbf586
        version: v1
    spec:
      containers:
      - image: ghcr.io/adiprerepa/slate-controller:latest
        imagePullPolicy: Always
        name: slate-controller
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: slate-controller-sa
      serviceAccountName: slate-controller-sa
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: slate-controller
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
status:
  observedGeneration: 2
  replicas: 0
