apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: "2023-11-17T20:30:22Z"
  generation: 2
  labels:
    app: details
    pod-template-hash: 7bfcb6b64c
    version: v1
  name: details-v1-7bfcb6b64c
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: details-v1
    uid: 5046d5cd-aa3e-436c-be57-f1322029acfd
  resourceVersion: "169771"
  uid: 14c69dba-0c3d-4df2-8dab-9b5f4c256d40
spec:
  replicas: 0
  selector:
    matchLabels:
      app: details
      pod-template-hash: 7bfcb6b64c
      version: v1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-11-17T20:30:22Z"
      creationTimestamp: null
      labels:
        app: details
        pod-template-hash: 7bfcb6b64c
        version: v1
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-details-v1:1.18.0
        imagePullPolicy: IfNotPresent
        name: details
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookinfo-details
      serviceAccountName: bookinfo-details
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 2
  replicas: 0
