apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "2"
    deployment.kubernetes.io/max-replicas: "3"
    deployment.kubernetes.io/revision: "17"
  creationTimestamp: "2023-12-01T20:52:52Z"
  generation: 1
  labels:
    app: ratings
    pod-template-hash: 564f9f5c69
    version: v1
  name: ratings-v1-564f9f5c69
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: ratings-v1
    uid: 2dce12dd-c6ca-4368-b0f5-b5fe24f5ae89
  resourceVersion: "2566295"
  uid: 2c30cde4-5ac8-4e31-b0ff-eae1c8ce8d13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      pod-template-hash: 564f9f5c69
      version: v1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-12-01T14:48:52-06:00"
      creationTimestamp: null
      labels:
        app: ratings
        pod-template-hash: 564f9f5c69
        version: v1
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-ratings-v1:1.18.0
        imagePullPolicy: IfNotPresent
        name: ratings
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookinfo-ratings
      serviceAccountName: bookinfo-ratings
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: ratings
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
status:
  fullyLabeledReplicas: 1
  observedGeneration: 1
  replicas: 1
