apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "2"
    deployment.kubernetes.io/max-replicas: "3"
    deployment.kubernetes.io/revision: "11"
  creationTimestamp: "2023-11-28T07:08:51Z"
  generation: 4
  labels:
    app: reviews
    pod-template-hash: 766d887b9d
    version: v3
  name: reviews-v3-766d887b9d
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: reviews-v3
    uid: fc3efd42-e3b9-4963-b627-42ec9557656f
  resourceVersion: "1937926"
  uid: 9c7739e9-f165-4d3e-a148-86a8ec8c7905
spec:
  replicas: 0
  selector:
    matchLabels:
      app: reviews
      pod-template-hash: 766d887b9d
      version: v3
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-11-17T20:34:40Z"
      creationTimestamp: null
      labels:
        app: reviews
        pod-template-hash: 766d887b9d
        version: v3
    spec:
      containers:
      - env:
        - name: LOG_DIR
          value: /tmp/logs
        image: docker.io/istio/examples-bookinfo-reviews-v3:1.18.0
        imagePullPolicy: IfNotPresent
        name: reviews
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /opt/ibm/wlp/output
          name: wlp-output
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookinfo-reviews
      serviceAccountName: bookinfo-reviews
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: reviews
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
      volumes:
      - emptyDir: {}
        name: wlp-output
      - emptyDir: {}
        name: tmp
status:
  observedGeneration: 4
  replicas: 0
