apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "2"
    deployment.kubernetes.io/max-replicas: "3"
    deployment.kubernetes.io/revision: "17"
  creationTimestamp: "2023-12-01T20:52:51Z"
  generation: 2
  labels:
    app: details
    pod-template-hash: 749ffb45fc
    version: v1
  name: details-v1-749ffb45fc
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: details-v1
    uid: 5046d5cd-aa3e-436c-be57-f1322029acfd
  resourceVersion: "2566377"
  uid: 93596ca2-b162-4fee-be06-c8b2ec0c4256
spec:
  replicas: 2
  selector:
    matchLabels:
      app: details
      pod-template-hash: 749ffb45fc
      version: v1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-12-01T14:48:52-06:00"
      creationTimestamp: null
      labels:
        app: details
        pod-template-hash: 749ffb45fc
        version: v1
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-details-v1:1.18.0
        imagePullPolicy: IfNotPresent
        name: details
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookinfo-details
      serviceAccountName: bookinfo-details
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: details
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
status:
  availableReplicas: 1
  fullyLabeledReplicas: 2
  observedGeneration: 2
  readyReplicas: 1
  replicas: 2
