apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: "2023-11-17T20:30:22Z"
  generation: 2
  labels:
    app: productpage
    pod-template-hash: 65fb545fb5
    version: v1
  name: productpage-v1-65fb545fb5
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: productpage-v1
    uid: c18c93bd-42ac-4820-8519-2f73bd1b84f5
  resourceVersion: "169781"
  uid: 7ddb120f-e232-4319-b2dd-854b3f9d1be6
spec:
  replicas: 0
  selector:
    matchLabels:
      app: productpage
      pod-template-hash: 65fb545fb5
      version: v1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-11-17T20:30:22Z"
        prometheus.io/path: /metrics
        prometheus.io/port: "9080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: productpage
        pod-template-hash: 65fb545fb5
        version: v1
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-productpage-v1:1.18.0
        imagePullPolicy: IfNotPresent
        name: productpage
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookinfo-productpage
      serviceAccountName: bookinfo-productpage
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
status:
  observedGeneration: 2
  replicas: 0
