apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "2"
    deployment.kubernetes.io/max-replicas: "3"
    deployment.kubernetes.io/revision: "15"
  creationTimestamp: "2023-12-01T20:48:52Z"
  generation: 4
  labels:
    app: details
    pod-template-hash: 5c5f9f67d4
    version: v1
  name: details-v1-5c5f9f67d4
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: details-v1
    uid: 5046d5cd-aa3e-436c-be57-f1322029acfd
  resourceVersion: "2566105"
  uid: 63d6faf8-4a4c-4ce5-9ec2-c98cb50b9382
spec:
  replicas: 0
  selector:
    matchLabels:
      app: details
      pod-template-hash: 5c5f9f67d4
      version: v1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-12-01T14:48:52-06:00"
      creationTimestamp: null
      labels:
        app: details
        pod-template-hash: 5c5f9f67d4
        version: v1
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-details-v1:1.18.0
        imagePullPolicy: IfNotPresent
        name: details
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookinfo-details
      serviceAccountName: bookinfo-details
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: details
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
status:
  observedGeneration: 4
  replicas: 0
