apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "8"
  creationTimestamp: "2023-11-17T19:36:29Z"
  generation: 2
  labels:
    app: ratings
    pod-template-hash: 5c98c95dfd
    version: v1
  name: ratings-v1-5c98c95dfd
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: ratings-v1
    uid: 2dce12dd-c6ca-4368-b0f5-b5fe24f5ae89
  resourceVersion: "168900"
  uid: 36c03b95-a8d4-4598-b97a-7c2c57cb7cbc
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ratings
      pod-template-hash: 5c98c95dfd
      version: v1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-11-17T19:36:29Z"
      creationTimestamp: null
      labels:
        app: ratings
        pod-template-hash: 5c98c95dfd
        version: v1
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-ratings-v1:1.18.0
        imagePullPolicy: IfNotPresent
        name: ratings
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookinfo-ratings
      serviceAccountName: bookinfo-ratings
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 2
  replicas: 0
