apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "3"
    deployment.kubernetes.io/max-replicas: "4"
    deployment.kubernetes.io/revision: "10"
  creationTimestamp: "2023-11-17T20:34:41Z"
  generation: 5
  labels:
    app: details
    pod-template-hash: 5b5f64b97f
    version: v1
  name: details-v1-5b5f64b97f
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: details-v1
    uid: 5046d5cd-aa3e-436c-be57-f1322029acfd
  resourceVersion: "1926672"
  uid: b1d062ce-1404-43aa-9e12-10a645df0aeb
spec:
  replicas: 0
  selector:
    matchLabels:
      app: details
      pod-template-hash: 5b5f64b97f
      version: v1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-11-17T20:34:40Z"
      creationTimestamp: null
      labels:
        app: details
        pod-template-hash: 5b5f64b97f
        version: v1
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-details-v1:1.18.0
        imagePullPolicy: IfNotPresent
        name: details
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookinfo-details
      serviceAccountName: bookinfo-details
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 5
  replicas: 0
