apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-11-16T20:16:10Z"
  name: kube-proxy
  namespace: kube-system
  resourceVersion: "260"
  uid: 85f4874e-d6e3-45b8-b455-5acf25851899
rules:
- apiGroups:
  - ""
  resourceNames:
  - kube-proxy
  resources:
  - configmaps
  verbs:
  - get
