apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-11-16T20:16:08Z"
  name: kubeadm:nodes-kubeadm-config
  namespace: kube-system
  resourceVersion: "204"
  uid: ac9a31f9-9650-4477-9d66-d5802c6363b1
rules:
- apiGroups:
  - ""
  resourceNames:
  - kubeadm-config
  resources:
  - configmaps
  verbs:
  - get
