apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2023-11-16T21:22:18Z"
  labels:
    install.operator.istio.io/owning-resource: installed-state-eastwest
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.20.0
    release: istio
  name: istio-eastwestgateway-sds
  namespace: istio-system
  resourceVersion: "5790"
  uid: 7a6e634b-de09-4e8d-ad7c-633caa068929
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-eastwestgateway-sds
subjects:
- kind: ServiceAccount
  name: istio-eastwestgateway-service-account
