apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-11-16T20:16:08Z"
  name: kubeadm:kubelet-config
  namespace: kube-system
  resourceVersion: "207"
  uid: a65aa119-3b33-44c6-97b9-5460b2d416a7
rules:
- apiGroups:
  - ""
  resourceNames:
  - kubelet-config
  resources:
  - configmaps
  verbs:
  - get
