apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-11-16T21:22:18Z"
  labels:
    install.operator.istio.io/owning-resource: installed-state-eastwest
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.20.0
    release: istio
  name: istio-eastwestgateway-sds
  namespace: istio-system
  resourceVersion: "5784"
  uid: 03461d4a-8bf1-4f1e-8095-fe9e5051641d
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
