apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-11-16T20:16:07Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system::extension-apiserver-authentication-reader
  namespace: kube-system
  resourceVersion: "191"
  uid: 25e5fd4b-298a-4041-bcb9-2fe6aee0cf02
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:kube-controller-manager
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:kube-scheduler
