apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app":"metallb"},"name":"pod-lister","namespace":"metallb-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"pod-lister"},"subjects":[{"kind":"ServiceAccount","name":"speaker","namespace":"metallb-system"}]}
  creationTimestamp: "2023-11-17T20:43:28Z"
  labels:
    app: metallb
  name: pod-lister
  namespace: metallb-system
  resourceVersion: "171031"
  uid: 553c4b19-7ecb-455c-b9ae-076ff5a18891
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-lister
subjects:
- kind: ServiceAccount
  name: speaker
  namespace: metallb-system
