apiVersion: v1
data:
  secretkey: SjJsUlFDTmRFeUN3S2ZTZkUrYXpmZw==
kind: Secret
metadata:
  creationTimestamp: "2023-11-17T20:43:29Z"
  name: memberlist
  namespace: metallb-system
  ownerReferences:
  - apiVersion: apps/v1
    kind: Deployment
    name: controller
    uid: 5eb13fd3-63bd-48a2-b7f5-011cfdd65dd9
  resourceVersion: "171076"
  uid: c95e6281-b993-4385-9e3f-d9efdfb63ba7
type: Opaque
