apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-11-16T20:16:19Z"
  name: service-account-controller
  namespace: kube-system
  resourceVersion: "289"
  uid: c831042e-2d07-40a1-bf5a-2357c3d58a8c
