apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"slate-controller","service":"slate-controller"},"name":"slate-controller","namespace":"default"},"spec":{"ports":[{"name":"http","port":8000,"targetPort":8080}],"selector":{"app":"slate-controller"}}}
  creationTimestamp: "2023-11-17T18:54:43Z"
  labels:
    app: slate-controller
    service: slate-controller
  name: slate-controller
  namespace: default
  resourceVersion: "156542"
  uid: 649213a0-b6cc-418d-9edf-774210982d09
spec:
  clusterIP: 10.103.153.133
  clusterIPs:
  - 10.103.153.133
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: slate-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
