apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-11-16T21:02:33Z"
  name: default
  namespace: istio-system
  resourceVersion: "3994"
  uid: 4661f19d-2f67-4baf-99e2-9f292e618e89
