apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-11-16T21:13:03Z"
  labels:
    app: istio-reader
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Base
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.20.0
    release: istio
  name: istio-reader-service-account
  namespace: istio-system
  resourceVersion: "4967"
  uid: 59c2c420-6ed2-465a-8bb3-0d1d589e6b39
