apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"account":"reviews"},"name":"bookinfo-reviews","namespace":"default"}}
  creationTimestamp: "2023-11-16T21:02:34Z"
  labels:
    account: reviews
  name: bookinfo-reviews
  namespace: default
  resourceVersion: "4037"
  uid: ef4abea2-25df-4d7b-98de-ddb2a5986afe
