apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"k8s-app":"flannel"},"name":"flannel","namespace":"kube-flannel"}}
  creationTimestamp: "2023-11-16T20:18:33Z"
  labels:
    k8s-app: flannel
  name: flannel
  namespace: kube-flannel
  resourceVersion: "557"
  uid: 0fdc0cee-7ceb-41d6-a578-813064750790
