apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"account":"productpage"},"name":"bookinfo-productpage","namespace":"default"}}
  creationTimestamp: "2023-11-16T21:02:35Z"
  labels:
    account: productpage
  name: bookinfo-productpage
  namespace: default
  resourceVersion: "4081"
  uid: 7c6a9dbc-d010-49b1-b0f4-37f0eff79d75
