apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"metallb"},"name":"speaker","namespace":"metallb-system"}}
  creationTimestamp: "2023-11-17T20:43:27Z"
  labels:
    app: metallb
  name: speaker
  namespace: metallb-system
  resourceVersion: "171024"
  uid: 821ad4d9-fe04-4dc9-b598-954a400d7c68
