apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-11-16T20:16:08Z"
  name: daemon-set-controller
  namespace: kube-system
  resourceVersion: "220"
  uid: 6b5d57e9-16ed-4751-a484-d780503cda0f
