apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-11-16T20:16:20Z"
  name: clusterrole-aggregation-controller
  namespace: kube-system
  resourceVersion: "299"
  uid: 8b57cb07-cc98-4435-8d2d-fad03348821d
