apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-11-16T20:16:08Z"
  name: root-ca-cert-publisher
  namespace: kube-system
  resourceVersion: "209"
  uid: 7b141b6d-1c0e-4e97-957a-dd728e31fd2a
