apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"account":"details"},"name":"bookinfo-details","namespace":"default"}}
  creationTimestamp: "2023-11-16T21:02:34Z"
  labels:
    account: details
  name: bookinfo-details
  namespace: default
  resourceVersion: "4004"
  uid: b527352d-6210-4903-b791-32f2335fbebf
