apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-11-16T21:22:18Z"
  labels:
    app: istio-eastwestgateway
    install.operator.istio.io/owning-resource: installed-state-eastwest
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: eastwestgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.20.0
    release: istio
    topology.istio.io/network: network1
  name: istio-eastwestgateway-service-account
  namespace: istio-system
  resourceVersion: "5774"
  uid: b54d3785-9aae-422e-ae7d-dc4d513a73d7
