apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"account":"ratings"},"name":"bookinfo-ratings","namespace":"default"}}
  creationTimestamp: "2023-11-16T21:02:34Z"
  labels:
    account: ratings
  name: bookinfo-ratings
  namespace: default
  resourceVersion: "4019"
  uid: c2732d9e-53c0-4ef4-972b-660332dfed14
