apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-11-16T20:16:19Z"
  name: statefulset-controller
  namespace: kube-system
  resourceVersion: "296"
  uid: d922fc44-27ba-41d7-bacc-446eb0815806
