apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-11-16T20:16:21Z"
  name: endpoint-controller
  namespace: kube-system
  resourceVersion: "306"
  uid: fc1581c6-5ff8-42fa-82b0-fb6dbc854f89
