apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-11-16T20:16:20Z"
  name: endpointslicemirroring-controller
  namespace: kube-system
  resourceVersion: "297"
  uid: a9e175f2-ae69-40c4-bf26-6961e7662a48
