apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"productpage","service":"productpage"},"name":"productpage","namespace":"default"},"spec":{"ports":[{"name":"http","port":9080}],"selector":{"app":"productpage"}}}
  creationTimestamp: "2023-11-16T21:02:35Z"
  labels:
    app: productpage
    service: productpage
  name: productpage
  namespace: default
  resourceVersion: "4075"
  uid: f2a5a9d6-2ffc-42d1-a6a4-56d49cd3d226
spec:
  clusterIP: 10.98.97.39
  clusterIPs:
  - 10.98.97.39
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: productpage
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
