apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"slate-global-controller","service":"slate-global-controller"},"name":"slate-global-controller","namespace":"default"},"spec":{"ports":[{"name":"http","port":8080,"targetPort":8080}],"selector":{"app":"slate-global-controller"}}}
  creationTimestamp: "2023-11-17T05:32:10Z"
  labels:
    app: slate-global-controller
    service: slate-global-controller
  name: slate-global-controller
  namespace: default
  resourceVersion: "61094"
  uid: a75022a4-3475-4818-a410-a6e1f81376aa
spec:
  clusterIP: 10.109.66.239
  clusterIPs:
  - 10.109.66.239
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: slate-global-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
