apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-11-16T20:16:19Z"
  name: service-controller
  namespace: kube-system
  resourceVersion: "290"
  uid: f2b3cef5-d7dc-474c-ac3d-55278b2b1769
