apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-11-16T20:16:19Z"
  name: namespace-controller
  namespace: kube-system
  resourceVersion: "288"
  uid: a1bb6a65-7ade-4c25-bb2a-05077d3a6f77
