apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions.istio.io/v1alpha1","kind":"WasmPlugin","metadata":{"annotations":{},"name":"slate-wasm-plugin","namespace":"default"},"spec":{"imagePullPolicy":"Always","url":"oci://ghcr.io/adiprerepa/slate-plugin:latest","vmConfig":{"env":[{"name":"HOSTNAME","valueFrom":"HOST"},{"name":"ISTIO_META_WORKLOAD_NAME","valueFrom":"HOST"},{"name":"ISTIO_META_CLUSTER_ID","valueFrom":"HOST"},{"name":"ISTIO_META_NODE_NAME","valueFrom":"HOST"},{"name":"ISTIO_META_INTERCEPTION_MODE","valueFrom":"HOST"},{"name":"ISTIO_META_OWNER","valueFrom":"HOST"},{"name":"ISTIO_META_MESH_ID","valueFrom":"HOST"},{"name":"TRUST_DOMAIN","valueFrom":"HOST"},{"name":"ISTIO_META_NETWORK","valueFrom":"HOST"}]}}}
  creationTimestamp: "2023-11-17T18:57:00Z"
  generation: 2
  name: slate-wasm-plugin
  namespace: default
  resourceVersion: "163237"
  uid: 64ebd312-653e-4426-ad3a-5826b4b4f6f8
spec:
  imagePullPolicy: Always
  url: oci://ghcr.io/adiprerepa/slate-plugin:latest
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_CLUSTER_ID
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_INTERCEPTION_MODE
      valueFrom: HOST
    - name: ISTIO_META_OWNER
      valueFrom: HOST
    - name: ISTIO_META_MESH_ID
      valueFrom: HOST
    - name: TRUST_DOMAIN
      valueFrom: HOST
    - name: ISTIO_META_NETWORK
      valueFrom: HOST
