apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-local-vs
spec:
  hosts:
  - helloworld.sample.svc.cluster.local
  http:
  - name: "cluster-1-local"
    match:
    - headers:
        foo:
          exact: bar
    route:
    - destination:
        host: helloworld.sample.svc.cluster.local 
        subset: west
  - name: "cluster-2-local"
    match:
    - sourceLabels:
        topology.istio.io/network: network2
    route:
    - destination:
        host: helloworld.sample.svc.cluster.local 
        subset: east
  - name: "the-rest"
    route:
    - destination:
        host: helloworld.sample.svc.cluster.local 
