

# ingressgw
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: slate-wasm-plugin
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: oci://ghcr.io/adiprerepa/slate-igw-timebomb-plugin:latest
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_REGION
      value: "ingress"
