apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld
spec:
  host: helloworld.sample.svc.cluster.local
  subsets:
  - name: west
    labels:
      topology.istio.io/network: network1
  - name: east
    labels:
      topology.istio.io/network: network2
