apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: slate-wasm-plugin
  namespace: default
spec:
  selector:
    matchLabels:
      app: httpbin
  url: oci://ghcr.io/adiprerepa/slate-plugin:latest
  vmConfig:
    env:
      - name: HOSTNAME
        valueFrom: HOST
      - name: WORKLOAD_NAME
        valueFrom: ISTIO_META_WORKLOAD_NAME
