apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: slate-wasm-plugin
  namespace: default
spec:
  url: oci://ghcr.io/adiprerepa/slate-plugin:latest
  imagePullPolicy: Always
  vmConfig:
    env:
    - name: HOSTNAME
      valueFrom: HOST
    - name: ISTIO_META_WORKLOAD_NAME
      valueFrom: HOST
    - name: ISTIO_META_CLUSTER_ID
      valueFrom: HOST
    - name: ISTIO_META_NODE_NAME
      valueFrom: HOST
    - name: ISTIO_META_INTERCEPTION_MODE
      valueFrom: HOST
    - name: ISTIO_META_OWNER
      valueFrom: HOST
    - name: ISTIO_META_MESH_ID
      valueFrom: HOST
    - name: TRUST_DOMAIN
      valueFrom: HOST
    - name: ISTIO_META_NETWORK
      valueFrom: HOST
